chat/urls.py
# manager/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('add-product/', views.add_product, name='add-product'),
    path('cart/', views.cart, name='cart'),
    path('pay/', views.pay, name='pay'),
    path('success/', views.success, name='success'),
    path('new-bill/', views.new_bill, name='new-bill'),
    path('detail/<int:product_id>', views.detail, name='detail'),
    path('search/', views.search, name='search'),
    path('remove/', views.remove, name='remove'),
    path('logout/', auth_views.LogoutView.as_view(next_page="/"), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name="home/login.html"), name='login'),
    path('register/', views.register, name='register'),
    path('new-product/', views.new_product, name='new-product'),
    path('profile/', views.profile, name='profile'),
    path('bill-detail/<int:id>', views.bill_detail, name='bill-detail'),
    path('finish/<int:id>', views.finish, name = 'finish'),
]

smart/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('home.urls')),
                  path('chat/',include("chat.urls")),
                  path('manager/',include("manager.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'home.views.error'
# handler500 = 'home.views.error'

home/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Cover(models.Model):
    name = models.CharField(max_length=100)
    img = models.ImageField(blank=True, null=True)


class Category(models.Model):
    name = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    img = models.ImageField(blank=True, null=True)
    detail = models.CharField(blank=True, null=True, max_length=200)

    def __str__(self):
        return self.name


class Product_Image(models.Model):
    img = models.ImageField(blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class Direction(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Table(models.Model):
    name = models.CharField(max_length=100)
    direction = models.ForeignKey(Direction, null=True, on_delete=models.CASCADE)
    rfid = models.CharField(blank=True, null=True, max_length=200)

    def __str__(self):
        return self.name


class Bill(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    order_method = models.BooleanField(default=False)
    table = models.ForeignKey(Table, null=True, on_delete=models.CASCADE)
    address = models.CharField(blank=True, null=True, max_length=200)
    phone_number = models.CharField(blank=True, null=True, max_length=15)
    creation_date = models.DateTimeField(null=True)
    paid = models.BooleanField(default=False)
    finished = models.BooleanField(default=False)

    def get_date(self):
        return self.creation_date

    def __str__(self):
        return str(self.id)


class Bill_detail(models.Model):
    bill = models.ForeignKey(Bill, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def total_price(self):
        return self.quantity * self.product.price


class Sex(models.Model):
    name = models.CharField(max_length=10)


class UserProfile(models.Model):
    user = models.ForeignKey(User, unique=True, on_delete=models.CASCADE)
    birthday = models.DateField(null=True)
    sex = models.ForeignKey(Sex, null=True, on_delete=models.CASCADE)
    img = models.ImageField(blank=True, null=True)
    phone_number = models.CharField(max_length=15, null=True)
    address = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.user.username)


class Wallet(models.Model):
    user = models.ForeignKey(User, unique=True, on_delete=models.CASCADE)
    balance = models.IntegerField(default=0)
    point = models.IntegerField(default=0)

    def __str__(self):
        return str(self.user.username)

home/forms.py
from django import forms
import re
from django.contrib.auth.models import User
from .models import Product, Product_Image, UserProfile, Wallet
from django.core.exceptions import ObjectDoesNotExist


class RegistrationForm(forms.Form):
    username = forms.CharField(label='Tài khoản', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms.CharField(label='Mật khẩu', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Nhập lại mật khẩu', widget=forms.PasswordInput())

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2 and password1:
                return password2
        raise forms.ValidationError("Mật khẩu không hợp lệ")

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError("Tên tài khoản có kí tự đặc biệt")
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError("Tài khoản này đã tồn tại")

    def save(self):
        User.objects.create_user(username=self.cleaned_data['username'], email=self.cleaned_data['email'],
                                 password=self.cleaned_data['password1'])
        UserProfile.objects.create(user=User.objects.get(username=self.cleaned_data['username']))
        Wallet.objects.create(user=User.objects.get(username=self.cleaned_data['username']))


class NewProduct(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class AddProduct_Image(forms.ModelForm):
    class Meta:
        model = Product_Image
        fields = '__all__'
        exclude = ('product',)

home/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django.http import HttpResponse
from django.shortcuts import render, redirect
from manager import views as manage_view

from chat.models import Conversation
from home.cart import Cart
from home.forms import RegistrationForm, NewProduct
from home.models import Product, Table, Cover, UserProfile, Wallet, Bill_detail, Bill


# Create your views here.
def index(request, search_key=None):
    if 'product' not in request.session:
        request.session['product'] = {}
    if search_key:
        Data = {'products': Product.objects.filter(name__icontains=search_key),
                'count': count(request)}
    else:
        Data = {'products': Product.objects.all(), 'covers': Cover.objects.all(), 'count': count(request)}

    # start: su ly chat
    if not request.session.session_key:
        request.session.save()

    session_key = request.session.session_key
    session = Session.objects.get(session_key=session_key)
    conversations = Conversation.objects.filter(member__in=[session])
    if request.user.id != 1:
        if conversations.count() < 1:
            cs = Conversation.objects.create()
            cs.member.add(session)
        else:
            cs = conversations[0]
        for ss in Session.objects.all():
            session_data = ss.get_decoded()
            if session_data != {}:
                uid = session_data.get('_auth_user_id')
                if uid == '1' and ss not in cs.member.all():
                    cs.member.add(ss)
    Data["conversations"] = conversations
    Data["user_name"] = request.user
    Data["SID"] = request.session.session_key
    # end: su ly chat

    return render(request, 'home/index.html', Data)


def count(request):
    if 'product' not in request.session:
        return 0
    result = 0
    for item, val in request.session['product'].items():
        result += val
    return result


def add_product(request):
    product_id = request.GET.get('product_id')
    if product_id in request.session['product']:
        request.session['product'][product_id] += 1
    else:
        request.session['product'][product_id] = 1
    return HttpResponse(count(request))


def get_price(product_id):
    return Product.objects.get(id=product_id).price


def get_name(product_id):
    return Product.objects.get(id=product_id).name


def get_url(product_id):
    return Product.objects.get(id=product_id).img.url


def sum_price(request):
    result = 0
    if 'product' in request.session:
        for product_id in request.session['product']:
            result += request.session['product'][product_id] * get_price(product_id)
    return result


def get_product(request):
    items = {}
    if request.session.get('product'):
        for product in request.session['product']:
            item = {'name': get_name(product), 'price': get_price(product),
                    'quantity': request.session['product'][product],
                    'url': get_url(product), 'total_price': get_price(product) * request.session['product'][product]}
            items[product] = item
    return items


def get_method(request):
    return request.session.get('method')


def cart(request):
    Data = {'tables': Table.objects.all(), 'items': get_product(request), 'sum': sum_price(request),
            'count': count(request)}
    return render(request, 'home/cart.html', Data)


def detail(request, product_id):
    Data = {'product': Product.objects.get(id=product_id), 'count': count(request)}
    return render(request, 'home/detail.html', Data)


def search(request):
    return index(request, request.GET.get('search_key'))


def remove(request):
    product_id = request.GET.get('product_id')
    if product_id in request.session['product']:
        del request.session['product'][product_id]
    return cart(request)


def register(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],
                                    )
            login(request, new_user)
            return render(request, 'home/register-success.html')
    return render(request, 'home/register.html', {'form': form})


def error(request):
    return render(request, 'home/error.html')


def pay(request):
    method = request.POST.get('method')
    if method == 'table':
        request.session['method'] = 'table'
        request.session['table'] = request.POST.get('table')
    else:
        request.session['method'] = 'address'
        request.session['address'] = request.POST.get('address')
        request.session['phone_number'] = request.POST.get('phone_number')
    if request.user.is_authenticated:
        money = Wallet.objects.get(user=User.objects.get(username=request.user.username)).balance
        return render(request, 'home/pay.html',
                      {'money': money, 'sum': sum_price(request), 'balance': money - sum_price(request)})
    return render(request, 'home/pay.html', {'sum': sum_price(request)})


def success(request):
    if request.method == 'POST':
        Cart(request).order()
    return render(request, 'home/success.html')


def new_bill(request):
    Cart(request).new_bill(request)
    return index(request)


def new_product(request):
    if request.method == 'POST':
        form = NewProduct(request.POST)
        if form.is_valid():
            form.save()
            return index(request)
    f = NewProduct()
    return render(request, 'home/new-product.html', {'form': f})


def profile(request):
    data = UserProfile.objects.get(user=User.objects.get(username=request.user.username))
    money = Wallet.objects.get(user=User.objects.get(username=request.user.username))
    return render(request, 'home/profile.html', {'data': data, 'money': money})


def bill_detail(request, id):
    Data = {'items': Bill_detail.objects.filter(bill=Bill.objects.get(id=id)), 'id': id}
    return render(request, 'home/bill-detail.html', Data)


def finish(request, id):
    Bill.objects.filter(id=id).update(finished=True)
    return redirect('../manager/')

home/templates/home/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %} {% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'home/favicon/favicon.ico' %}"/>
</head>
<body>
<div id="header">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a class="social" href="{% url 'home:index' %}"><img src="{% static 'home/images/logo.png' %}" id="logo"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSmart"
                aria-controls="navbarSmart" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSmart">
            <ul class="navbar-nav" style="margin: 0 auto;">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'home:index' %}">Trang chủ</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Giới thiệu</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Liên hệ</a>
                </li>
                {% if user.username == 'admin' %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">Quản lý</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                {% endif %}
            </ul>
            {% if user.is_authenticated %}
                <div class="text-style">Xin chào <a class="text-style" href="{% url 'home:profile' %}">{{ user.username }}</a> | <a
                        class="text-style" href="{% url 'home:logout' %}">Đăng xuất</a></div>
            {% else %}
                <div><a class="text-style" href="{% url 'home:login' %}">Đăng nhập</a> | <a class="text-style"
                                                                                            href="{% url 'home:register' %}">Tạo
                    tài khoản</a>
                </div>
            {% endif %}
            <a class="text-style" href="https://www.facebook.com/VirustotalUITEdition" data-toggle="tooltip"
               title="Facebook"><i id="social-fb" class="fa fa-facebook-square fa-2x social"></i></a>
            <a class="text-style" href="https://plus.google.com/u/0/100716740184414915598" data-toggle="tooltip"
               title="Google+"><i id="social-gp" class="fa fa-google-plus-square fa-2x social"></i></a>
            <a class="text-style" href="mailto:vietxuan071097@gmail.com" data-toggle="tooltip" title="Mail"><i
                    id="social-em" class="fa fa-envelope-square fa-2x social"></i></a>
        </div>
    </nav>
</div>
<div id="main">
    {% block base %}
    {% endblock %}
</div>
<div id="footer">
    <div class="text-center" style="background-color: #6351ce;">
        <p style="color: #6351ce;">Django Project by Nguyễn Viết Xuân</p>
    </div>
    <div class="container text-center text-md-left mt-5">
        <div class="container row">
            <div class="col-md-4">
                <div class="text-center">
                    <h6 style="color:#188C18" class="text-uppercase font-weight-bold">CÔNG TY S*MART THUẦN VIỆT</h6>
                    <hr style="width: 120px;">
                    <br>
                </div>
                <span><strong>Địa chỉ:</strong> 102 đường 17, Linh Chiểu, Thủ Đức.<br></span>
                <span><strong>Số điện thoại:</strong> 0888 001 200<br></span>
                <span><strong>Mail:</strong> info@smartthuanviet.com<br></span>
                <span><strong>Web:</strong> smartthuanviet.com<br></span>
            </div>
            <div class="col-md-8">
                <!--Google map-->
                <iframe src="https://maps.google.com/maps?q=CÔNG TY S*MART THUẦN VIỆT&t=&z=13&ie=UTF8&iwloc=&output=embed"
                        frameborder="0"
                        style="border:0" allowfullscreen></iframe>
                <!--Google Maps-->
            </div>
        </div>
    </div>
    <hr size="50" color="red"/>
</div>

<script src="{% static 'home/js/jquery-3.3.1.slim.min.js' %}"></script>
<script src="{% static 'home/js/popper.min.js' %}"></script>
<script src="{% static 'home/js/bootstrap.min.js' %}"></script>
<script src="{% static 'home/js/jvs.js' %}"></script>
</body>
</html>

home/templates/home/bill-detail.html
{% extends 'home/index-base.html' %}
{% load staticfiles %}
{% block title %}Bill-detail{% endblock %}
{% block index-base %}
{% if items %}
<div class="container text-center">
    <h1>Chi tiết đơn hàng</h1>
    <table class="table" style="background-color:#FFFFFF;">
        <thead>
            <tr>
                <th scope="col">Sản phẩm</th>
                <th scope="col">Số lượng</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td>
                    <a href="{% url 'home:detail' item.product.id %}"><img src="{{item.product.img.url}}" alt="" style="height: 60px; width: 90px"></a>
                    <br>
                    <p>{{item.product.name}}</p>
                </td>
                <td>{{item.quantity}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="text-center">
        <button type="button" onclick="finish({{id}})" id="button-add" class="btn">Hoàn thành</button>
    </div>
    <br>
</div>
<script>
    function finish(id)
    {
        var xmlHttp = new XMLHttpRequest();
        xmlHttp.onreadystatechange = function() {
        if (xmlHttp.readyState == 4 && xmlHttp.status == 200)
            {
                alert("Đã hoàn thành");
                window.location.href="/manager/";
            }
        }
        xmlHttp.open("GET", "/finish/"+id, true);
        xmlHttp.send(null);
    }
</script>
{% else %}
<h1>Hiện không có đơn hàng nào</h1>
{% endif %}
{% endblock %}

home/templates/home/cart.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% load filter %}
{% block title %}Cart{% endblock %}
{% block base %}
    {% if items %}
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-9">
                    <table class="table text-center" style="background-color:#FFFFFF;">
                        <thead>
                        <tr>
                            <th scope="col">Sản phẩm</th>
                            <th scope="col">Giá</th>
                            <th scope="col">Số lượng</th>
                            <th scope="col">Tổng</th>
                            <th scope="col">Xóa</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in items %}
                            <tr>
                                <td>
                                    <a href="{% url 'home:detail' item %}"><img
                                            src="{{ items|get_item:item|get_item:'url' }}" alt=""
                                            style="height: 60px; width: 90px"></a>
                                    <br>
                                    <p>{{ items|get_item:item|get_item:'name' }}</p>
                                </td>
                                <td>{{ items|get_item:item|get_item:'price'|format_num}}</td>
                                <td>{{ items|get_item:item|get_item:'quantity' }}</td>
                                <td>{{ items|get_item:item|get_item:'total_price'|format_num }}</td>
                                <td>
                                    <form action="{% url 'home:remove' %}" method="get">
                                        <input type="hidden" value="{{ item }}" name="product_id">
                                        <button class="btn close" style="float: none" type="submit"><i
                                                class="fa fa-trash"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col-md-3">
                    <div style="background-color:#FFFFFF;">
                        <br>
                        <h3 class="text-center">Thông tin đặt hàng</h3>
                        <ul>
                            <li>Số lượng: <span>{{ count }}</span></li>
                            <li>Tổng tiền: <span>{{ sum|format_num }}</span></li>
                        </ul>
                        <div class="container">
                            <hr>
                            <h4>Hình thức giao hàng</h4>
                            <form action="{% url 'home:pay' %}" method="post">
                                {% csrf_token %}
                                <label for="table">
                                    <input id="table" onclick="checked_change()" type="radio" name="method"
                                           value="table"
                                           checked> Tại quán
                                </label>
                                <label for="address">
                                    <input id="address" onclick="checked_change()" type="radio" name="method"
                                           value="address">
                                    Giao hàng
                                </label>
                                <div id="chose-table" style="display: block">
                                    Chọn vị trí ngồi:
                                    <label for="table">
                                        <select class="form-control" id="table" name="table">
                                            {% for table in tables %}
                                                <option>{{ table.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </label>
                                    <hr>
                                </div>
                                <div id="chose-address" style="display: none">
                                    <label for="address">Địa chỉ:</label><br>
                                    <textarea name="address" id="address"
                                              style="width: 100%"></textarea><br>
                                    <label for="phone_number">Số điện thoại:</label><br>
                                    <input id="phone_number" type="text" name="phone_number" maxlength="10"
                                           style="width: 100%">
                                    <hr>
                                </div>
                                <div class="text-center">
                                    <input class="btn button-add" type="submit" value="Thanh toán">
                                </div>
                            </form>
                        </div>
                        <br>
                    </div>
                    <br>
                </div>
            </div>
        </div>
    {% else %}
        <div class="container text-center">
            <br>
            <h1>Giỏ hàng trống</h1>
            <a href="{% url 'home:index' %}"><img class="logo-smart ball" src="{% static 'home/images/icon.png' %}"
                                                  alt="Logo smart"></a>
            <br>
            <br>
        </div>
    {% endif %}
{% endblock %}

home/templates/home/error.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block title %}Error{% endblock %}
{% block base %}
<div class="text-center">
    <h1>Trang không tồn tại</h1>
    <p>Quay lại <a href="{% url 'home:index' %}">trang chủ</a></p>
</div>
{% endblock %}

home/templates/home/index-base.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block base %}
    {% block index-base %}
    {% endblock %}
        <a class="cart-button" href="{% url 'home:cart' %}">
            <img class="img-button" src="{% static 'home/images/icon.png' %}" alt="Logo smart">
            <p class="badge cart-button ball" id="count-items">{{ count }}</p>
        </a>
    <a class="chat-button" onclick="test()">
        <img class="img-button" src="http://noibo.beurervietnam.com/wp-content/uploads/2018/05/chat.png"
             alt="Logo smart">
    </a>
    <script>
        function test() {
            var $chatbox = $('.chatbox');

            $chatbox.toggleClass('chatbox--closed');
        }
    </script>
{% endblock %}

home/templates/home/login.html
{% extends 'home/user-base.html' %}
{% load staticfiles %}
{% block title %}Login{% endblock %}
{% block user-base %}
    <form method="POST">
        {% csrf_token %}
        {% for key, value in form.erros.item %}
            {{ value }}
        {% endfor %}
        <p><input type="username" class="form-control" id="username" name="{{ form.username.name }}"
                  placeholder="Tài khoản"></p>
        <p><input type="password" class="form-control" id="pwd" name="{{ form.password.name }}"
                  placeholder="Mật khẩu"></p>
        <div class="checkbox">
            <label><input type="checkbox"> Nhớ mật khẩu</label>
        </div>
        <input type="hidden" name="next" value="/">
        <div class="text-center">
            <button class="btn button-add" type="submit" name="submit">Đăng nhập</button>
        </div>
        <br>
    </form>
{% endblock %}

home/templates/home/new-product.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% block title %}New product{% endblock %}
{% block base %}
    <form action="{% url 'home:new-product' %}" method="post">
    {% csrf_token %}
        <ul>
            {% for f in form %}
                <li>{{ f.label }}:{{ f }}</li>
            {% endfor %}
        </ul>
        <input class="btn button-add" type="submit" value="Thêm món">
    </form>
{% endblock %}

home/templates/home/pay.html
{% extends 'home/base.html' %}
{% load staticfiles %}
{% load filter %}
{% block title %}Pay{% endblock %}
{% block base %}
    <div class="container" style="background-color: white">
        <br>
        <h4>Hình thức thanh toán</h4>
        <form action="{% url 'home:success' %}" method="post">
            {% csrf_token %}
            {% if user.is_authenticated %}
                <label for="money">
                    <input id="money" type="radio" onclick="pay_checked()" name="pay" value="money" checked> <i
                        class="fa fa-money fa-2x text-style"
                        aria-hidden="true"></i> Tiền
                    mặt
                </label>
                <label for="card">
                    <input id="card" type="radio" onclick="pay_checked()" name="pay" value="card"> <i
                        class="fa fa-credit-card fa-2x text-style"
                        aria-hidden="true"></i> Ví nội bộ
                </label>
                <p><strong>Số tiền cần thanh toán:</strong> {{ sum|format_num }}</p>
                <div id="chose-card" style="display: none">
                    <p><strong>Số tiền trong ví: </strong>{{ money|format_num }}</p>
                    <p><strong>Còn lại:</strong> {{ balance|format_num }}</p>
                </div>
                <hr>
            {% else %}
                <label for="money">
                    <input id="money" type="radio" name="pay" value="money" checked> <i
                        class="fa fa-money fa-2x text-style"
                        aria-hidden="true"></i> Tiền
                    mặt
                </label>
                <p><strong>Số tiền cần thanh toán:</strong> {{ sum|format_num }}</p>
                <hr>
            {% endif %}
            <input name="sum" value="{{ sum }}" type="hidden">
            <div class="text-center">
                <input class="btn button-add" type="submit" value="Gọi món">
            </div>
            <br>
        </form>
    </div>
{% endblock %}

home/templates/home/register-success.html
{% extends 'home/user-base.html' %}
{% load staticfiles %}
{% block title %}Success{% endblock %}
{% block user-base %}
    <div class="text-center text-style">
        <h3>Đăng ký tài khoản thành công</h3>
        <a href="{% url 'home:index' %}"><p class="text-style">Về trang chủ</p></a>
    </div>
{% endblock %}

home/templates/home/register.html
{% extends 'home/user-base.html' %}
{% load staticfiles %}
{% block title %}Register{% endblock %}
{% block user-base %}
    <form method="POST">
        {% csrf_token %}
        {% for key, value in form.erros.item %}
            {{ value }}
        {% endfor %}
        <p><input type="username" class="form-control" id="username" name="{{ form.username.name }}"
                  placeholder="Tài khoản"></p>
        <p><input type="email" class="form-control" id="email" name="{{ form.email.name }}"
                  placeholder="Mail"></p>
        <p><input type="password" class="form-control" id="password1" name="{{ form.password1.name }}"
                  placeholder="Mật khẩu"></p>
        <p><input type="password" class="form-control" id="password1" name="{{ form.password2.name }}"
                  placeholder="Nhập lại mật khẩu"></p>
        <input type="hidden" name="next" value="/">
        <div class="text-center">
            <button class="btn button-add" type="submit" name="submit">Đăng ký</button>
        </div>
    </form>
{% endblock %}

home/templates/home/success.html
{% extends 'home/user-base.html' %}
{% load staticfiles %}
{% block title %}Success{% endblock %}
{% block user-base %}
    <div class="text-center text-style">
        <h3>Đặt hàng thành công</h3>
        <a class="text-style" href="{% url 'home:cart' %}">Xem lại đơn hàng</a> | <a class="text-style" href="{% url 'home:new-bill' %}">Đơn hàng mới</a>
    </div>
{% endblock %}